### ISSUE TITLE
Model cost calculator fails with NPE for some adapters

### ISSUE THREAD

**Issue by astsiapanay** [epam/ai-dial-core#201]
See an error log below:
```
2024-02-07 09:05:34.781 WARN [vert.x-eventloop-thread-1] Failed to calculate cost for model=gemini-pro-vision. Trace: 1ada789786ddf29c1377fb1ed5873c80. Span: 8a652bd28cc4151c
java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "com.fasterxml.jackson.databind.node.ArrayNode.get(int)" because "choices" is null
	at com.epam.aidial.core.util.ModelCostCalculator.getResponseContentLength(ModelCostCalculator.java:103)
	at com.epam.aidial.core.util.ModelCostCalculator.calculate(ModelCostCalculator.java:65)
	at com.epam.aidial.core.util.ModelCostCalculator.calculate(ModelCostCalculator.java:39)
```

Per conversation with @adubovik:
We don't need to count pricing.unit from the model config any longer. Adapters are responsible to calculate token usage statistics correctly. The core should take token usage statistics from the field `usage` in the model response to calculate the cost.

**Comment by astsiapanay** [comment]
@adubovik please review the issue. Is it correct?

**Comment by adubovik** [comment]
This is correct. 

I believe introduction of `char_without_whitespace` enum case was a mistake. However we still may need `unit` field in the future, e.g. if we introduce enum case `token_1k` to reduce number of zeros in the cost fields.

**Comment by adubovik** [comment]
Ah, I was wrong. We actually need to handle `char_without_whitespace` enum case properly.

The `unit` field in the `pricing` config could be understood as a function which turnes the request into a **billable units**.

For the majority models the billable units coincide with the tokens (`pricing.unit == token`).
But for some [models](https://cloud.google.com/vertex-ai/pricing) the billable unit isn't the same as a token, so we have to specify some custom strategy to compute the billable units _(e.g. compute all the visible characters in the prompt and completion, which is `char_without_whitespace` enum case)_.

Finally, the NPE error `"choices" is null` could be triggered, because a streaming chunk could contain a JSON with an error:

```json
{ "error": { "message": "error message" } }
```

We need to take this into account.
